import { EncounterBlueprint } from "../types";

export const ENCOUNTER_CATALOG: EncounterBlueprint[] = [
  {
    id: "neo-rooftop-sprint",
    lane: "mobility",
    title: "Neo Rooftop Sprint",
    description: "Dash across unstable rooftops while drones sweep lanes.",
    baseDifficulty: 3,
    requiredElements: ["fire"],
    teaches: ["water"],
    rewardWeight: 1.0,
  },
  {
    id: "laser-bridge-gauntlet",
    lane: "mobility",
    title: "Laser Bridge Gauntlet",
    description: "Double-jump timing challenge over animated beam bridges.",
    baseDifficulty: 6,
    requiredElements: ["water"],
    teaches: ["ice"],
    rewardWeight: 1.2,
  },
  {
    id: "spore-swarm-hall",
    lane: "swarm",
    title: "Spore Swarm Hall",
    description: "Contain a flood of fungal drones before they overwhelm your lane.",
    baseDifficulty: 4,
    requiredElements: ["fire"],
    teaches: ["fire"],
    rewardWeight: 1.05,
  },
  {
    id: "mycelium-siege",
    lane: "swarm",
    title: "Mycelium Siege",
    description: "Crossfire survival room with escalating enemy clusters.",
    baseDifficulty: 7,
    requiredElements: ["fire", "water"],
    teaches: ["ice"],
    rewardWeight: 1.3,
  },
  {
    id: "clockwork-riddles",
    lane: "puzzle",
    title: "Clockwork Riddles",
    description: "Rotate rune wheels to disable barrier chains under time pressure.",
    baseDifficulty: 3,
    requiredElements: ["water"],
    teaches: ["water"],
    rewardWeight: 1.0,
  },
  {
    id: "mirror-vault",
    lane: "puzzle",
    title: "Mirror Vault",
    description: "Sequence elemental mirrors in the correct order to unlock relic shards.",
    baseDifficulty: 6,
    requiredElements: ["water", "ice"],
    teaches: ["nature"],
    rewardWeight: 1.25,
  },
  {
    id: "arcane-interceptors",
    lane: "tactics",
    title: "Arcane Interceptors",
    description: "Use focused bursts to stagger shielded elites before their ultimates fire.",
    baseDifficulty: 5,
    requiredElements: ["fire"],
    teaches: ["ice"],
    rewardWeight: 1.1,
  },
  {
    id: "void-snare-chess",
    lane: "tactics",
    title: "Void Snare Chess",
    description: "Turn-based combat puzzle with trap placement and flanking counters.",
    baseDifficulty: 8,
    requiredElements: ["ice"],
    teaches: ["void"],
    rewardWeight: 1.4,
  },
  {
    id: "warden-duel",
    lane: "boss",
    title: "Warden Duel",
    description: "Boss chamber duel with telegraphed burst windows and punish phases.",
    baseDifficulty: 7,
    requiredElements: ["fire", "water"],
    teaches: ["ice"],
    rewardWeight: 1.35,
  },
  {
    id: "dark-mycelius-aspect",
    lane: "boss",
    title: "Dark Mycelius Aspect",
    description: "High-pressure raid style encounter with phase transitions.",
    baseDifficulty: 9,
    requiredElements: ["fire", "water", "ice"],
    teaches: ["void"],
    rewardWeight: 1.5,
  },
];
